"""
Template for synthesized tools.
The forge prompt instructs the LLM to generate code following this structure.
"""

TOOL_TEMPLATE = '''\
# /// script
# requires-python = ">=3.11"
# dependencies = [{dependencies}]
# ///
"""
Tool: {name}
Generated by Ghost v{ghost_version}
Prompt version: {prompt_version}
Capabilities: {capabilities}
"""

import sys
import json

def main():
    {body}

if __name__ == "__main__":
    try:
        result = main()
        if result is not None:
            print(json.dumps(result, indent=2, default=str))
    except Exception as e:
        print(json.dumps({{"error": str(e)}}), file=sys.stderr)
        sys.exit(1)
'''
