"""
Quarantine — holds synthesized tools pending user approval.

Tools are written to ~/.ghost/quarantine/ as Python scripts.
Each tool has PEP 723 inline metadata for dependency management.

Flow: forge → quarantine → user reviews → approve → registry
                                        → reject  → delete
"""
import hashlib
import logging
import uuid
from pathlib import Path
from typing import Any

from ghost.constants import QUARANTINE_DIR, VERSION

logger = logging.getLogger(__name__)


class QuarantineManager:
    """Manages tools pending user approval."""

    def __init__(self, ghost_home: Path, writer: Any) -> None:
        self.quarantine_dir = ghost_home / QUARANTINE_DIR
        self.quarantine_dir.mkdir(parents=True, exist_ok=True)
        self.writer = writer

    async def add(self, name: str, description: str, code: str,
                  dependencies: list[Any] | None = None, capabilities: list[str] | None = None,
                  prompt_version: str = "v1") -> dict[str, Any]:
        """
        Write a synthesized tool to quarantine.

        Returns:
            dict with tool metadata (id, name, file_path, etc.)
        """
        tool_id = str(uuid.uuid4())
        short_hash = hashlib.sha256(code.encode()).hexdigest()[:8]

        # Build PEP 723 script
        dep_lines = ""
        if dependencies:
            dep_strs = []
            for dep in dependencies:
                if hasattr(dep, "name"):
                    has_ver = getattr(dep, "version_spec", "")
                    name = getattr(dep, "name")
                    spec = f'"{name}{dep.version_spec}"' if has_ver else f'"{name}"'
                elif isinstance(dep, dict):
                    spec = f'"{dep["name"]}{dep.get("version_spec", "")}"'
                else:
                    spec = f'"{dep}"'
                dep_strs.append(f"#   {spec},")
            dep_lines = "\n".join(dep_strs)

        script = f'''# /// script
# requires-python = ">=3.11"
# dependencies = [
{dep_lines}
# ]
# ///
"""
Tool: {name}
Generated by Ghost v{VERSION}
Prompt version: {prompt_version}
Capabilities: {", ".join(capabilities or [])}
"""

import sys
import json

{code}

if __name__ == "__main__":
    try:
        result = main()
        if result is not None:
            print(json.dumps(result, indent=2, default=str))
    except Exception as e:
        print(json.dumps({{"error": str(e)}}), file=sys.stderr)
        sys.exit(1)
'''

        # Write to quarantine directory
        file_name = f"{name}_{short_hash}.py"
        file_path = self.quarantine_dir / file_name
        file_path.write_text(script)

        source_hash = hashlib.sha256(code.encode()).hexdigest()
        caps = capabilities or []

        # Register in DB as quarantined
        await self.writer.write(
            """INSERT INTO tools (id, name, version, description, file_path, source_hash,
                                  status, capabilities, prompt_version, ghost_api_version)
               VALUES (?, ?, 1, ?, ?, ?, 'quarantined', ?, ?, ?)""",
            (tool_id, name, description, str(file_path), source_hash,
             str(caps), prompt_version, VERSION)
        )

        tool_info = {
            "id": tool_id,
            "name": name,
            "description": description,
            "file_path": str(file_path),
            "source_hash": source_hash,
            "status": "quarantined",
            "capabilities": caps,
            "code_preview": code[:500],
        }

        logger.info(f"Tool '{name}' quarantined at {file_path}")
        return tool_info

    async def list_pending(self) -> list[dict[str, Any]]:
        """List all quarantined tools."""
        cursor = await self.writer.db.execute(
            "SELECT * FROM tools WHERE status = 'quarantined' ORDER BY created_at DESC"
        )
        return [dict(r) for r in await cursor.fetchall()]

    async def get(self, tool_id: str) -> dict[str, Any] | None:
        """Get a quarantined tool by ID."""
        cursor = await self.writer.db.execute(
            "SELECT * FROM tools WHERE id = ? AND status = 'quarantined'",
            (tool_id,)
        )
        row = await cursor.fetchone()
        return dict(row) if row else None

    async def approve(self, tool_id: str) -> dict[str, Any] | None:
        """Approve a tool — changes status to 'approved'."""
        await self.writer.write(
            "UPDATE tools SET status = 'approved' WHERE id = ? AND status = 'quarantined'",
            (tool_id,)
        )
        # Return updated tool
        cursor = await self.writer.db.execute("SELECT * FROM tools WHERE id = ?", (tool_id,))
        row = await cursor.fetchone()
        return dict(row) if row else None

    async def reject(self, tool_id: str) -> bool:
        """Reject and delete a quarantined tool."""
        tool = await self.get(tool_id)
        if not tool:
            return False

        # Delete file
        file_path = Path(tool["file_path"])
        if file_path.exists():
            file_path.unlink()

        # Remove from DB
        await self.writer.write(
            "DELETE FROM tools WHERE id = ? AND status = 'quarantined'",
            (tool_id,)
        )

        logger.info(f"Tool '{tool['name']}' rejected and deleted")
        return True
